### PR TITLE
dark theme proposal 

### PR DESCRIPTION
**Pull request by tst32**
create ```toml(dark).xml``` with dark theme syntax highlight. 
image
after merge i will delete my fork

### CODE REVIEW

**Comment by Theodor-Lindberg** [comment]
Hi, thank you for the contribution! I will try to find time to review it in the next couple of days.

**Comment by Theodor-Lindberg** [comment]
Hi,

I finally tried the new file. The problem that I see with both the existing XML and the PR is the background color. The new dark theme will only work for one specific background, the same with the existing file. A better solution is to set the background to "none" so it works for all backgrounds.

I'll attach the new XML file [here](https://github.com/Theodor-Lindberg/NPP-TOML-Syntax/files/6541920/TOML.zip) for you to review, if you like it I can simply update the XML and README then push directly to the master branch. How does that sound? 

Sorry for the late reply.

**Comment by tst32** [comment]
Adopted transparent backround in file TOML(dark).xml - with your attached file, and add a file with dark theme on #2e2e2e  color  and named it as notepadplusplus original theme TOML(DansLeRuSH-Dark).xml

**Comment by cooperjaXC** [comment]
@Theodor-Lindberg, is there any reason we can't merge this pull request to give multiple dark theme TOML notepad++ options and fix Issue #4? I like @tst32's `TOML(dark)` theme for viewing my .toml files. My vote is to reopen and merge this pull request.

**Pull request closed without merging**
