### PR TITLE
Orange color for single quotes strings

### PR DESCRIPTION
**Pull request by xhit**
Strings that are encapsulated with quotes have orange color FF8000, add this color for single quotes too.

### CODE REVIEW

**Comment by Theodor-Lindberg** [comment]
Hi, thank you for the contribution. I will test it tomorrow!

**Comment by Theodor-Lindberg** [comment]
I noticed some strange behavior when the single quote strings are used within brackets. 

See if you can reproduce it with the following code snippet:
```
'single-quotes are orange' 
hosts = [   
  "alpha",   
  "omega",   
  'single-quotes are purple'   
]   
```
The settings seem to be correct so I don't know what causes this behavior and why we don't get the same issue with double-quoted strings.

**Comment by xhit** [comment]
PTAL.

**Comment by xhit** [comment]
PING

**Comment by Theodor-Lindberg** [comment]
Hi,

Thanks for the ping, I forgot about the pull request when I started working again.

It looks like it got fixed so I will go ahead and merge it!

Thanks

**Comment by xhit** [comment]
Perfecto. The commit updating the example has a missed quote

```toml
hosts = [
  "alpha",
  "omega",
  'beta
]
```

**Comment by Theodor-Lindberg** [comment]
Well spotted!

I'll update the screenshot as well while I'm at it.

**Pull request merged**
